variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:          # List of stages for jobs, and their order of execution
  - config
  - build
  - deploy

default:
  tags: [werf]

before_script:
  - type trdl && . $(trdl use werf 1.2 stable)
  - type werf && source $(werf ci-env gitlab --as-file)
  - HOST_NAME=${CI_SERVER_HOST:7}

# configure:
#   stage: config
#   script:
#     - git clone --branch $CI_COMMIT_BRANCH --recurse-submodules -j8 http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.1437703-cz27429.tw1.ru/p2-seabattle/p2-config-instance.git
#     - dotnet build p2-config-instance/src/Config/Config.Paper/Config.Paper.csproj --output app
#     - app/Config.Paper plugins/p2-ignore
#     - rm -rf app
#     - rm -rf p2-config-instance

werf build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "pipeline"
  script:
    - werf build

werf deploy master:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "dev"
  script:
    - werf converge --repo=registry.$HOST_NAME:32000/p2-paper-instance \
        --insecure-registry \
        --set "HOST_NAME=$HOST_NAME"