apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2-paper-instance
spec:
  selector:
    matchLabels:
      app: p2-paper-instance
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: p2-paper-instance
        lang: java
        cycle: plugin
    spec:
      containers:
      - name: p2-paper-instance
        image: {{ index $.Values.werf.image "p2-paper-instance" }}
        imagePullPolicy: Always
        ports:
        - containerPort: 25565
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        lifecycle:
          preStop:
            exec:
              command: [
                "/rcon/p2-rcon", 
                "--ip", "127.0.0.1:1008",
                "--pass", "test_pass",
                "--key", "test",
                "--request-json", "{\"test\":\"message\"}"
              ]
        readinessProbe:
          tcpSocket:
            port: 1008
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: p2-paper-instance-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: p2-paper-instance
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565